# feeder
feeder: feeders.feeder.Feeder
test_feeder_args:
  data_path: /media/22905553/F020DDF820DDC5AE/Action_Dataset/Fall_detection_data/upfall_openpose/xfall/fall4/val_joint.npy
  label_path: /media/22905553/F020DDF820DDC5AE/Action_Dataset/Fall_detection_data/upfall_openpose/xfall/fall4/val_label.pkl 
  debug: False
  normalization: True
  random_choose: False
  window_size: 1145
  
# model
model: model.model.Model
model_args:
  num_class: 2
  num_point: 25  
  max_frame: 1145
  graph: 'graph.ntu_rgb_d.AdjMatrixGraph'
  act_type: 'relu'
  bias: True
  edge: True
  block_size: 41

# test
phase: test
device: [0]
test_batch_size: 64
#weights: /home/uniwa/students3/students/22905553/linux/phd_codes/My_part_based_convolution/uwa3d_test_v8/weights/weights-32-224.pt
#weights: /home/uniwa/students3/students/22905553/linux/phd_codes/Fall_detection/ntu_xsub/weights/weights-39-12207.pt
weights: /home/uniwa/students3/students/22905553/linux/phd_codes/Light_Fall/up_fall4/weights/weights-11-572.pt
work_dir: ./eval/ntu/xsub/joint/
save_score: True
